server:
  port: 3303

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: e-commerce-config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dxhyh/e-commerce-server-config  # 你的配置文件所在仓库
          default-label: master # 配置文件分支
          search-paths:  # 配置文件所在根目录
          username: dxhyh # 用户名
          password: Ab19928093058 # 密码